added a new section for copyDependencies
OpenLiberty/guide-jpa-intro pull request #211
Opened 2023-11-24 19:48 UTC by saumyapandyaa

2023-11-28 17:05 UTC, gkwan-ibm requested changes
hi @saumyapandyaa 

I suggest to move the "Third-party libraries for Open Liberty with Maven" subsection under "Configuring JPA" section.
- it should similar to the content in deepdive guide 
   - "To use a PostgreSQL database, ..." -> "To use a Derby database, ..."
   - replace the pom.xml
-  the subsection title to be "Setting database libraries"

2024-08-23 14:58 UTC, gkwan-ibm commented
dev content review:
- move the subsection to a new section after the "Performing CRUD operations using JPA" section
- rename the subsection title to "Configuring the Derby driver and the Liberty"
- explain adding 3 derby dependencies in `<dependencies></dependencies>` to download the derby libraries to local
- explain using `copyDependencies` to copy the derby libraries to Liberty shared resources directory
- explain the shared resources directory is used in the `derbyJDBCLib` of server.xml
  - hotspot to this [lines](https://github.com/OpenLiberty/guide-jpa-intro/blob/6c87982f3039b451893daa6e7dce9a45b722ae70/finish/backendServices/src/main/liberty/config/server.xml#L20-L22)
- make sure this arrange does not affect the flow that the app can work at the "Running the application" and "Testing the application"

2024-08-28 19:03 UTC, shin19991207 approved these changes
LGTM

2024-08-28 19:28 UTC, dmuelle requested changes
ID review

2024-08-28 19:28 UTC, dmuelle commented on README.adoc
> +== Configuring the Derby driver and the Liberty
```suggestion
== Configuring the Derby driver and the Liberty Maven plugin
```

2024-08-28 19:28 UTC, dmuelle commented on README.adoc
> +Three required Derby dependencies are added to the [hotspot=dependencies file=0]`dependencies` configuration for Maven to download the Derby libraries locally. The [hotspot=copyDependencies file=0]`c
```suggestion
This configuration adds three required Derby dependencies to the [hotspot=dependencies file=0]`dependencies` configuration so Maven can download the Derby libraries locally. The [hotspot=copyDependencies file=0]`copyDependencies` configuration instructs the Liberty Maven plug-in to copy the Derby libraries to the Liberty shared resources directory that is specified through the [hotspot=location file=0]`location` configuration, and is referenced in the [hotspot=shared-dir file=1]`derbyJDBCLib` `library` configuration of the `server.xml` file.
```

2024-08-28 19:39 UTC, dmuelle approved these changes

2024-08-28 19:43 UTC, gkwan-ibm approved these changes

2024-08-28 19:43 UTC, merged